env-config-vars: &env-config-vars
  INSPECT_PY_LOGGER_FILE: /home/logs/inspect.log
  INSPECT_PY_LOGGER_LEVEL: DEBUG
  
# Common settings for all aisi-basic-agent configurations
common: &common_settings
  start: aisi-basic-agent/start.sh
  dockerfile: aisi-basic-agent/Dockerfile
  mount_docker_socket: true

# Dev configurations

aisi-basic-agent-openai-dev:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: openai/gpt-4o
    MAX_TIME_IN_HOURS: 3
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    PB_CODE_ONLY: "true"

aisi-basic-agent-openai-o3-dev:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: openai/o3-mini-2025-01-31
    MAX_TIME_IN_HOURS: 3
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    PB_CODE_ONLY: "true"


aisi-basic-agent-openai-gpt-4.1-dev:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: openai/gpt-4.1-2025-04-14
    MAX_TIME_IN_HOURS: 3
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    PB_CODE_ONLY: "true"

aisi-basic-agent-gemini-litellm-dev:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: openai/gemini-2.5-pro-preview-03-25
    MAX_TIME_IN_HOURS: 0.1
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    OPENAI_BASE_URL: http://192.168.1.77:4000/v1/
    PB_CODE_ONLY: "true"

aisi-basic-agent-anthropic-dev:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: anthropic/claude-3-7-sonnet-20250219
    MAX_TIME_IN_HOURS: 3
    ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
    PB_CODE_ONLY: "true"

aisi-basic-agent-gemini-dev:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: google/gemini-2.5-pro-preview-03-25
    MAX_TIME_IN_HOURS: 3
    GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
    PB_CODE_ONLY: "true"
    ITERATIVE_AGENT: true

aisi-basic-agent-gemini-vertex-dev:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: vertex/gemini-2.5-pro-preview-03-25
    MAX_TIME_IN_HOURS: 0.1
    GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
    GOOGLE_CLOUD_PROJECT: benchflow-vertex
    GOOGLE_CLOUD_LOCATION: us-central1
    GOOGLE_APPLICATION_CREDENTIALS: benchflow-vertex-183bfe073901.json
    GOOGLE_GENAI_USE_VERTEXAI: true
    PB_CODE_ONLY: "true"

aisi-basic-agent-llama4-dev:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: openrouter/meta-llama/llama-4-maverick
    MAX_TIME_IN_HOURS: 120
    OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
    PB_CODE_ONLY: "true"
    ITERATIVE_AGENT: true

aisi-basic-agent-r1-dev:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: openrouter/deepseek-ai/DeepSeek-R1
    MAX_TIME_IN_HOURS: 0.5
    OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

aisi-basic-agent-claude-3-7-sonnet-dev:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: openrouter/anthropic/claude-3.7-sonnet:thinking
    MAX_TIME_IN_HOURS: 0.1
    OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

# OpenAI

aisi-basic-agent-4o:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: openai/gpt-4o
    MAX_TIME_IN_HOURS: 12
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

aisi-basic-agent-o1:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: openai/o1
    MAX_TIME_IN_HOURS: 12
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

aisi-basic-agent-o3-mini:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: openai/o3-mini-2025-01-31
    MAX_TIME_IN_HOURS: 12
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

# Anthropic

aisi-basic-agent-claude-3-5-sonnet:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: openrouter/anthropic/claude-3.5-sonnet
    MAX_TIME_IN_HOURS: 12
    OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

aisi-basic-agent-claude-3-7-sonnet:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: openrouter/anthropic/claude-3.7-sonnet:thinking
    MAX_TIME_IN_HOURS: 12
    OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

# Google

aisi-basic-agent-gemini-2.0-flash:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: google/gemini-2.0-flash
    MAX_TIME_IN_HOURS: 12
    GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}

# DeepSeek

aisi-basic-agent-r1:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: openrouter/deepseek-ai/DeepSeek-R1
    MAX_TIME_IN_HOURS: 12
    OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}

# IterativeAgent

aisi-basic-agent-iterative-o1:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: openai/o1
    MAX_TIME_IN_HOURS: 12
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    ITERATIVE_AGENT: true

aisi-basic-agent-iterative-o3-mini:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: openai/o3-mini-2025-01-31
    MAX_TIME_IN_HOURS: 12
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    ITERATIVE_AGENT: true

aisi-basic-agent-iterative-claude-3-5-sonnet:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: openrouter/anthropic/claude-3.5-sonnet
    MAX_TIME_IN_HOURS: 12
    OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
    ITERATIVE_AGENT: true

aisi-basic-agent-iterative-claude-3-7-sonnet:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: openrouter/anthropic/claude-3.7-sonnet:thinking
    MAX_TIME_IN_HOURS: 12
    OPENROUTER_API_KEY: ${{ secrets.OPENROUTER_API_KEY }}
    ITERATIVE_AGENT: true

aisi-basic-agent-iterative-o1-pb-code-only:
  <<: *common_settings
  env_vars:
    <<: *env-config-vars
    MODEL: openai/o1
    MAX_TIME_IN_HOURS: 12
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    ITERATIVE_AGENT: true
    PB_CODE_ONLY: "true"
